### ISSUE TITLE
Add `erpnext` to `required_apps` in `hooks.py`

### ISSUE THREAD

**Issue by MaxMorais** [frappe/schools#27]
References : https://discuss.erpnext.com/t/announcing-beta-schools-erpnext-com/10130/10

And https://github.com/frappe/frappe/blob/e3a2b1265cf291d8c295db4257bbd250dc2a6fc1/frappe/installer.py#L97

**Comment by neilLasrado** [comment]
@MaxMorais fixed it. Thanks for bringing it to our notice.
