### ISSUE TITLE
Error when adding new User

### ISSUE THREAD

**Issue by umairsy** [frappe/schools#48]
The account in question is only for one User. Following is the screenshot when I try adding new User. with validation message of User limit, it also shows message related to Employee User id (specific to ERPNext) and Welcome Email Sent.

![screen shot 2016-04-08 at 3 01 14 pm](https://cloud.githubusercontent.com/assets/910238/14380025/0bc6196c-fd9b-11e5-85e6-f126cd9ecade.png)

It should not check Employee master for the User ID.

Since User limit is exceed, Welcome Email should not be sent as well.

**Comment by neilLasrado** [comment]
This has been fixed
