### ISSUE TITLE
ERPNext related Roles should not be visible

### ISSUE THREAD

**Issue by umairsy** [frappe/schools#50]
If a Site only has School app installed on it, then in the User master, ERPNext related Roles should be hidden.

![screen shot 2016-04-08 at 3 34 30 pm](https://cloud.githubusercontent.com/assets/910238/14380852/84a089c2-fd9f-11e5-8928-7d520cc40f55.png)

**Comment by neilLasrado** [comment]
https://github.com/frappe/frappe/issues/1694
